spring:
  application:
    name: diary-backend

  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.eensskjncsooyuxbfokm
    password: Lakezzang123@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

ai:
  flux:
    base-url: "http://34.21.94.52:8000"

server:
  port: ${PORT:8080}
