spring:
  application:
    name: diary-backend

  datasource:
    # â¬‡ï¸ Supabaseê°€ ë³´ì—¬ì¤€ Session pooler ì—°ê²° ë¬¸ìì—´ ê¸°ì¤€
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.eensskjncsooyuxbfokm # Supabaseì—ì„œ ë³µì‚¬í•œ ì‚¬ìš©ìëª…
    password: Lakezzang123@ # ë„¤ DB ë¹„ë°€ë²ˆí˜¸
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3 # ğŸ”¥ í•µì‹¬: í’€ ì‚¬ì´ì¦ˆ í™• ì¤„ì´ê¸°
      minimum-idle: 1
      idle-timeout: 30000 # 30ì´ˆ
      connection-timeout: 20000 # 20ì´ˆ

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

ai:
  flux:
    base-url: "http://34.21.94.52:8000"

server:
  port: ${PORT:8080}
