spring:
  application:
    name: diary-backend

  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.eensskjncsooyuxbfokm
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000 # 30s
      max-lifetime: 600000 # 10min
      connection-timeout: 20000 # 20s

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

ai:
  flux:
    base-url: "http://34.21.94.52:8000"

server:
  port: ${PORT:8080}
